name: Graffo Design
favicon: null
layout_spectrum: 0.9710486894473433
typography_spectrum: 0.15994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdff'
    - '#569bdc'
    - '#0131b4'
    - '#215bbf'
    - '#094c5c'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
